spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 1KB
      max-request-size: 1KB
